language: python

virtualenv:
  system_site_packages: true

sudo: false

env:
  global:
    - FFTW_VERSION="3.3.4"
    - LAL_VERSION="6.15.0"
    - LALFRAME_VERSION="1.3.0"
    - LIBFRAME_VERSION="8.20"
    - LDAS_TOOLS_VERSION="2.4.1"

addons:
  apt:
    packages:
      # lal dependencies
      - pkg-config
      - python-all-dev
      - zlib1g-dev
      - libgsl0-dev
      - swig
      - python-numpy
      - python-scipy
      - bc
      # glue dependencies
      - python-m2crypto
      # misc python packages
      - python-matplotlib
      - texlive-latex-extra

before_install:
  # update pip
  - pip install -q --upgrade pip

  # build FFTW3
  - source .travis/build-with-autotools.sh http://www.fftw.org/fftw-${FFTW_VERSION}.tar.gz ./fftw-${FFTW_VERSION}

  # build numpy and scipy
  - travis_retry pip install -q numpy==1.9.1
  - travis_wait pip install -q scipy==0.16

  # build LAL packages
  - source .travis/build-with-autotools.sh http://software.ligo.org/lscsoft/source/lalsuite/lal-${LAL_VERSION}.tar.gz ./lal-${LAL_VERSION}
  - source .travis/build-with-autotools.sh http://software.ligo.org/lscsoft/source/lalsuite/lalframe-${LALFRAME_VERSION}.tar.gz ./lalframe-${LALFRAME_VERSION}

  # install build dependencies
  - travis_retry pip install -q tornado jinja2 GitPython

  # install cython
  - travis_retry pip install -q --install-option="--no-cython-compile" Cython

  # install python dependencies
  - travis_retry pip install -q matplotlib==1.3.1
  - travis_retry pip install -q astropy==1.0
  - travis_retry pip install -q h5py
  - travis_retry pip install -q unittest2
  - travis_retry pip install -q importlib
  - travis_retry pip install -q pytest
  - travis_retry pip install -q coveralls

  # install LSCSoft python packages
  - travis_retry pip install -q M2Crypto
  - travis_retry pip install -q kerberos
  - travis_retry pip install -q python-cjson
  - travis_retry pip install -q http://software.ligo.org/lscsoft/source/glue-1.49.1.tar.gz
  - travis_retry pip install -q http://software.ligo.org/lscsoft/source/dqsegdb-1.2.2.tar.gz

install:
  - python setup.py build

script:
  - coverage run --source=gwpy --omit="gwpy/tests/*,gwpy/*version*,gwpy/utils/sphinx/*" -m py.test -v
  - pip install .

after_success:
  - coveralls

notifications:
  slack:
    secure: jQdoSpwNbUnq0Eo7o6Ko7vuhu58LQdfy8jFKxLUnUjv/GLezK/PPAQCU9SgmyDPh1yD8sb5Xa8UtbNfGtpYdwBAGwZxPHz3oQQAflivFwcF6UP7/NlAB9muSOOnL0QfQyX1I4sIKOkX+gkl+TBciX4v58B8NUU02dDkwDqTLUqQ=
