version: 2

# -- templates --------------

run-tests: &run-tests
  name: Test
  command: bash -ex ci/test.sh

debian-build: &debian-build
  steps:
    - checkout
    - attach_workspace:
        at: .
    - run:
        name: Build
        command: bash -ex ci/install-debian.sh
    - run: *run-tests
    - store_test_results:
        path: test-reports
    - store_artifacts:
        path: test-reports
    - store_artifacts:
        path: "*.deb"

centos-build: &centos-build
  steps:
    - checkout
    - attach_workspace:
        at: .
    - run:
        name: Build
        command: bash -ex ci/install-el.sh
    - run: *run-tests
    - store_test_results:
        path: test-reports
    - store_artifacts:
        path: test-reports
    - store_artifacts:
        path: "*.rpm"

# -- jobs -------------------

jobs:
  sdist:
    docker:
      - image: python
    steps:
      - checkout
      - run:
          name: Build tarball
          command: python setup.py --quiet sdist --dist-dir .
      - persist_to_workspace:
          root: .
          paths:
            - gwpy-*.tar.*

  flake8:
    docker:
      - image: hoto/flake8:latest
    steps:
      - checkout
      - run:
          name: Lint
          command: |
            python -m pip install flake8-junit-report
            mkdir -p test-reports
            python -m flake8 --output-file test-reports/flake8.txt
            python -m junit_conversor test-reports/flake8.txt test-reports/junit.xml
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports

  debian:stretch:2.7:
    <<: *debian-build
    docker:
      - image: ligo/base:stretch
    environment:
      PYTHON_VERSION: "2.7"

  debian:stretch:3.5:
    <<: *debian-build
    docker:
      - image: ligo/base:stretch
    environment:
      PYTHON_VERSION: "3.5"

  el7:2.7:
    <<: *centos-build
    docker:
      - image: ligo/base:el7
    environment:
      PYTHON_VERSION: "2.7"

# -- workflow ---------------

workflows:
  version: 2
  build-and-test:
    jobs:
      - sdist
      - flake8
      - debian:stretch:2.7:
          requires:
            - sdist
      - debian:stretch:3.5:
          requires:
            - sdist
      - el7:2.7:
          requires:
            - sdist
